# -*- coding: utf-8 -*-
"""GRP4-Activity5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x5AqNdMGOtKWBP9oNopL3fq_FnwfqBVv

# CpE Elective 3 Laboratory (LBYCPC4) <br/>
#### Computer Vision and Deep Learning Elective Track
<br/>
<hr style="border:5px solid gray">

## Activity 5: Familiarization with Single Board Computer (SBC)

### Introduction
&emsp;&emsp;&emsp;In this activity, we will be familiarizing with the capabilities of a single board computer (SBC). Particularly, we will explore the capabilities of the Raspberry Pi as a versatile single-board computer (SBC) for implementing computer vision and deep learning algorithms on subsequent activities. As a low-cost, compact platform, the Raspberry Pi offers an accessible way to deploy real-world artificial intelligence applications, making it a valuable tool for students, hobbyists, and developers alike.

### Objectives
- Familiarize with Raspberry Pi's software and hardware capabilities
- Program the the Raspberry Pi's general purposes I/Os (GPIOs)
- Integrate the Raspberry Pi with a camera to capture real-time video streams

### Activity
For each tasks/steps asking for results/outputs, place the results in the provided markdown or code cells below each step.

**A. Basic Commands and GPIO Control of Single Board Computer**

For this task, you will be needing the following external circuit components:
* Raspberry Pi
* HDMI Adapter and Cable
* Breadboard
* Jumper wires (female-male)
* 4 pcs. LEDs (any color)
* 1 pc. push button
* 4 pcs. 220-ohm resistors

1. Connect an HDMI-compatible monitor, peripherals (e.g., mouse and keyboard), and lastly the power supply to the Raspberry Pi in that order. Open a Terminal and research for the commands to perform the following:
<ol type="a">
  <li>List all files in the current working diretory</li>
  <li>Show disk usage, available space on mounted file systems</li>
  <li>Display information about system memory usage (RAM and swap)</li>
  <li>Display network configuration, including IP address, interface names, and MAC addresses</li>
  <li>Display real-time system information such as CPU and memory usage, and running processes</li>
  <li>Open the Nano text editor to create a file "hello.txt" with your group member names and ID numbers as its contents</li>
</ol>

  Show the output of the terminal and the results for each task and document them in your final report.

`-- YOUR ANSWER HERE --`

2. Research for the layout of the Raspberry Pi 4 GPIO header. You will be needing it as a reference for the next steps.

`-- YOUR ANSWER HERE --`

3. We will be testing the GPIO for generating digital signals, 
particularly for blinking an LED. Connect one leg of the LED through the 220 ohm resistor to GPIO 17 pin and
one leg to a ground pin. Take a picture of your setup.

`-- YOUR ANSWER HERE --`

4. Open the Thonny Python IDE and create a new Python script named "blink_led.py" saved at the Documents folder. Enter the following simple code to blink the LED. Run the script and take a video of the setup to show that it is working.

```
  import RPi.GPIO as GPIO
  import time

  led_pin = 17
  GPIO.setmode(GPIO.BCM)
  GPIO.setup(led_pin, GPIO.OUT)

  try:
    while True:
      GPIO.output(led_pin, GPIO.HIGH)
      time.sleep(0.5)
      GPIO.output(led_pin, GPIO.LOW)
      time.sleep(0.5)
  except KeyboardInterrupt:
    GPIO.cleanup()
```

`-- YOUR ANSWER HERE --`

5. We will now be testing the GPIO to read in digital signals, particularly read the state of a push button. Connect one leg of the push button to GPIO 27 pin and the other leg to a ground pin. Take a picture of your setup.

`-- YOUR ANSWER HERE --`

6. In the Thonny Python IDE, create a new Python script named "button_led.py" saved at the Documents folder. Enter the following code to read the button's state and control the LED. Run the script and take a video of the setup to show that it is working.

```
  import RPi.GPIO as GPIO
  import time

  led_pin = 17
  button_pin = 27

  GPIO.setmode(GPIO.BCM)
  GPIO.setup(led_pin, GPIO.OUT)
  GPIO.setup(button_pin, GPIO.IN)

  try:
    while True:
      button_state = GPIO.input(button_pin)
      if button_state == GPIO.LOW:
        GPIO.output(led_pin, GPIO.HIGH)
      else:
        GPIO.output(led_pin, GPIO.LOW)
      time.sleep(0.02)
  except KeyboardInterrupt:
    GPIO.cleanup()
```

`-- YOUR ANSWER HERE --`

7. You may observe that the LED flickers whenever the button is not pressed. To eliminate this problem, look for the function call `GPIO.setup(button_pin, GPIO.IN)` in Step B.5 and specify the following keyword argument: `pull_up_down=GPIO.PUD_UP`. Explain why this change resolves the issue in your final report.

`-- YOUR ANSWER HERE --`

8. Connect the four (4) LEDs and a push button to the GPIO header properly. Then, create a new Python script named "led_pattern.py" saved at the Documents folder. When the program is executed, the 4 LEDs should show a simple moving light pattern across the LEDs, with one LED lit at a time. Pressing the push button should toggle the direction of movement. Provide the code below and take a video showing that is works. Put the shared video link in your final report.
"""

# -- YOUR CODE HERE -- #

"""**B. Connecting the Camera**

1. There are two (2) ways to connect a camera to Raspberry Pi: (1) through a dedicated camera serial interface (CSI) port, and (2) through USB port. For this activity, you will be using a USB camera. Connect the camera to USB 3.0 port.

2. Confirm that the USB camera was detected by opening the Terminal and running the following command:

  `v4l2-ctl --list-devices`

  Save the output and look for your USB camera name among the list and take note of its device path (usually `/dev/video0`)

`-- YOUR ANSWER HERE --`

3. Run the following command to check the available image resolutions that your camera can support:

  `v4l2-ctl --list-formats-ext`

`-- YOUR ANSWER HERE --`

4. In the Terminal, type the following commands to install the following packages:

  `sudo apt update`<br/>
  `sudo apt-get install -y ffmpeg fswebcam python3-opencv`

5. Take a picture of your Raspberry Pi setup by running the following command in the Terminal:

  `fswebcam -r $RESOLUTION --no-banner ~/Pictures/rpi_setup.jpg`

  `$RESOLUTION` should be replaced with the largest resolution supported by your camera (e.g., `1280x720` for 720p) as found in Step C.3. Retrieve the image and include it in your final report.

`-- YOUR ANSWER HERE --`

6. Take a 5-second video using the following command:

  `ffmpeg -f v4l2 -i $DEV -t 00:00:05 -vcodec libx264 ~/Videos/vid_test.mp4`

  `$DEV` should be replaced with the video device path as found in Step C.2. Retrieve the video and include it in your final report as a shared link.

`-- YOUR ANSWER HERE --`

7.  Open the Thonny Python IDE. Confirm first that OpenCV was installed properly by executing the following in the shell:

  `import cv2`<br/>
  `cv2.__version__`

`-- YOUR ANSWER HERE --`

8. Copy the following code into the IDE and save it to the Documents folder as a Python script named "opencv_cam.py":

  ```
  import cv2

  cam = cv2.VideoCapture(0) # you can change this based on the assigned number in Step C.2

  while True:
    ret, img = cam.read()
    cv2.imshow("Camera", img)
    if cv2.waitKey(1) == 27:
      break
  
  cam.release()
  cv2.destroyAllWindows()
  ```

  Take a video of the setup (you can use your mobile phones) with the running program on screen to show that it works. Share the video as a link in your final report.

`-- YOUR ANSWER HERE --`

9. Modify the code in Step C.8 so that you can save the camera stream as a video file using OpenCV. The video can be as short as five (5) seconds. Provide the code below and share the created video file as a link in your final report.
"""

# -- YOUR CODE HERE -- #

"""10. Modify the code in Step C.8 so that the program will save a frame if a button connected to the GPIO header pin is pressed. The program should not overwrite previously saved frames but instead use a sequential numbering scheme for file naming. You may choose any GPIO pin as long as it supports digital input. Provide the code below."""

# -- YOUR CODE HERE -- #

"""***

### Machine Problems

### References

[1] *Raspberry Pi 4 Model Specifications*. https://www.raspberrypi.com/products/raspberry-pi-4-model-b/specifications/

[2] *Raspberry Pi OS*. https://www.raspberrypi.com/software/

[3] *GPIO Pins | Physical Computing with Python*. https://projects.raspberrypi.org/en/projects/physical-computing/1

[4] *Install OpenCV on your Raspberry Pi*. https://raspberrypi-guide.github.io/programming/install-opencv

[5] *Working with USB webcams on your Raspberry Pi*. https://raspberrypi-guide.github.io/electronics/using-usb-webcams
"""
